server:
  port: 8080
# ? ???? ??? ??? ????
spring:
  application:
    name: well-plate
  profiles:
    active: default
  datasource:
    driver-class-name: org.postgresql.Driver # ?????? ???? ??? ??
    url: "jdbc:${db.engine}://${db.host}:${db.port},${db.host}:${db.port}/${db.dbname}?targetServerType=primary" # ?????? ?? URL
    username: "${db.username}"
    password: "${db.password}"
    connectionTestQuery: "SELECT 1"
    hikari:
      maximum-pool-size: 15   # ?? ??? ? ??
      minimum-idle: 15      # ?? ??? ? ??
      connection-timeout: 5000 # ??? ????
      validation-timeout: 2000 # ??? ??? ?? ????
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect # ?????? ???
    hibernate:
      ddl-auto: create-drop
#      ddl-auto: validate # create disabled: schema has been managed by flyway on docker-compose
    properties:
      format_sql: true
      show-sql:
        use_sql_comments: ${logging.default-show-sql}
        use_jdbc_metadata_defaults: ${logging.default-show-sql}
#  flyway:
#    enabled: true
#    create-schemas: true
#    baseline-on-migrate: true
#    baseline-version: 0
#    out-of-order: true


logging:
  pattern:
    correlation: "[%X{traceId:-} %X{spanId:-}] "
  level:
    root: ${logging.default-level}
    io: ${logging.default-level}
    jdk: ${logging.default-level}
    com: ${logging.default-level}
    org: ${logging.default-level}
    reactor: ${logging.default-level}


---
spring:
  config:
    import:
      - classpath:parameters/logging/logging.yml
      - classpath:parameters/db/db.yml