name: Deploy Spring Boot to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out the code
        uses: actions/checkout@v3


      #    러너 머신에 Gradle이 깔려 있지 않다면 gradlew 스크립트를 사용 (프로젝트 루트에 gradlew가 있다고 가정).
      - name: Build with Gradle
        run: ./gradlew clean build

      # 4. Spring Boot 애플리케이션 실행
      #    jar 파일이 build/libs 디렉토리에 있다고 가정
      - name: Run Spring Boot App
        run: |
          pkill -f wellplate-0.0.1-SNAPSHOT.jar || echo "기존 프로세스가 없습니다."
          java -jar build/libs/wellplate-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev