name: Deploy Spring Boot to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      #    러너 머신에 Gradle이 깔려 있지 않다면 gradlew 스크립트를 사용 (프로젝트 루트에 gradlew가 있다고 가정).
      - name: Build with Gradle
        run: ./gradlew clean build

      #    jar 파일이 build/libs 디렉토리에 있다고 가정
      - name: Run Spring Boot App
        run: |
          pkill -f wellplate-0.0.1-SNAPSHOT.jar || echo "기존 프로세스가 없습니다."
          nohup java -jar build/libs/wellplate-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev > /dev/null 2>&1 &

      - name: Wait for Application & Health Check
        run: |
          # 1. 일정 시간 대기
          echo "Waiting for the application to start..."
          sleep 60   # 서비스가 구동될 시간을 줍니다 (상황에 따라 조절)

          #    Spring Boot 에서 actuator 가 활성화되어 있고, 서버 포트가 8080 라고 가정
          echo "Checking Health..."
          curl --fail http://localhost:8080/actuator/health

          echo "Health Check OK!"